apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ophthalmoai
  namespace: ophthalmoai
spec:
  ingressClassName: nginx
  rules:
    - host: ophthalmoai.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
